### PR TITLE
an API to check if VF is bound to vfio-pci driver

### PR DESCRIPTION
**Pull request by girishmg**
Signed-off-by: Girish Moodalbail <gmoodalbail@nvidia.com>

### CODE REVIEW

**Comment by girishmg** [comment]
@adrianchiris @moshe010  can you PTAL?

**Comment by adrianchiris** [comment]
@girishmg can you provide a brief description why you would like this added and add UT for it in `sriovnet_test.go`

**Comment by girishmg** [comment]
@adrianchiris @moshe010 I have added unit tests and I have provided the reasoning for this PR.

**Comment by adrianchiris** [comment]
> VF2 below is bound to VFIO device or not

nit: thats VF1 according to the diagram.

LGTM, will fix this upon merge

**Pull request merged**
